begin;

create table if not exists public.tbl_strand (
  strand_id bigint generated by default as identity primary key,
  strand_name text not null,
  strand_description text not null default '',
  date_created timestamptz not null default now()
);

create table if not exists public.tbl_student (
  student_id bigint generated by default as identity primary key,
  "studentID_no" text not null unique,
  first_name text not null,
  middle_name text not null default '',
  last_name text not null,
  strand text not null default '',
  grade_level text not null default '',
  date_ofbirth text not null default '',
  gender text not null default '',
  complete_address text not null default '',
  email_address text not null default '',
  mobile_number text not null default '',
  username text not null unique,
  password text not null,
  account_status text not null default 'Active',
  date_created date not null default current_date
);

create table if not exists public.tbl_usermanagement (
  user_id bigint generated by default as identity primary key,
  complete_name text not null,
  designation text not null default '',
  email_address text not null default '',
  phone_number text not null default '',
  username text not null unique,
  password text not null,
  status text not null default 'Active',
  role text not null default ''
);

create table if not exists public.tbl_documentrequest (
  request_id bigint generated by default as identity primary key,
  control_no text not null,
  "studentID_no" text not null,
  document_name text not null,
  purpose_ofrequesting text not null default '',
  no_ofcopies text not null default '1',
  date_request text not null default '',
  date_releasing text not null default '',
  processing_officer text not null default '',
  status text not null default 'Received',
  "reference number" text not null default '',
  remarks text not null default '',
  student_id bigint not null,
  notif integer not null default 0
);

create index if not exists tbl_documentrequest_student_id_idx
  on public.tbl_documentrequest(student_id);
create index if not exists tbl_documentrequest_status_idx
  on public.tbl_documentrequest(status);

create table if not exists public.tbl_payment (
  payment_id bigint generated by default as identity primary key,
  control_no text not null,
  "studentID_no" text not null,
  document_name text not null,
  date_releasing text not null default '',
  reference_number text not null,
  student_id bigint not null,
  total_amount numeric not null default 0,
  amount_paid numeric not null default 0,
  date_ofpayment text not null default '',
  proof_ofpayment text not null default '',
  status text not null default 'Verified',
  date_created timestamptz not null default now()
);
create index if not exists tbl_payment_student_id_idx on public.tbl_payment(student_id);

create table if not exists public.app_sessions (
  session_id text primary key,
  payload text not null default '',
  expires_at timestamptz not null
);
create index if not exists app_sessions_expires_at_idx on public.app_sessions(expires_at);

alter table public.tbl_strand enable row level security;
alter table public.tbl_student enable row level security;
alter table public.tbl_usermanagement enable row level security;
alter table public.tbl_documentrequest enable row level security;
alter table public.tbl_payment enable row level security;
alter table public.app_sessions enable row level security;

revoke all on table public.tbl_strand from anon, authenticated;
revoke all on table public.tbl_student from anon, authenticated;
revoke all on table public.tbl_usermanagement from anon, authenticated;
revoke all on table public.tbl_documentrequest from anon, authenticated;
revoke all on table public.tbl_payment from anon, authenticated;
revoke all on table public.app_sessions from anon, authenticated;
grant all on table public.tbl_strand to service_role;
grant all on table public.tbl_student to service_role;
grant all on table public.tbl_usermanagement to service_role;
grant all on table public.tbl_documentrequest to service_role;
grant all on table public.tbl_payment to service_role;
grant all on table public.app_sessions to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into public.tbl_strand (strand_id, strand_name, strand_description, date_created) values
  (14, 'STEM', 'Science Technology Engineering and Mathematics- Academic Track', '2023-03-16 23:59:53+00'),
  (15, 'ABM', 'Accountancy Business and Management- Academic Track', '2023-03-17 00:01:09+00'),
  (16, 'HUMSS', 'Humanities and Social Sciences- Academic Track', '2023-03-17 00:02:24+00'),
  (17, 'TVL', 'Technical Vocational and Livelihood-Vocational Track', '2023-03-17 00:03:14+00')
on conflict (strand_id) do nothing;

insert into public.tbl_student (
  student_id, "studentID_no", first_name, middle_name, last_name, strand, grade_level,
  date_ofbirth, gender, complete_address, email_address, mobile_number, username,
  password, account_status, date_created
) values
  (2, 'STDNT-23983', 'maria cecilia', 'o', 'toledo', 'STEM', 'Grade 12', '2021-11-29', 'Female', 'mambugan', 'maria@gmail.com', '09365466666', 'maria', 'maria123', 'Active', '2021-11-18'),
  (4, 'STDNT-0433220', 'emil', 'l', 'murio', 'BS Computer Science', '3rd Year', '2021-11-24', 'Male', 'francisville', 'nario@gmail.com', '09654646456', 'nario', 'nario', 'Active', '2021-11-18'),
  (6, 'STDNT-2300340', 'erlin', 's', 'nidea', 'bachelor of science in business administration', '4th Year', '2021-11-19', 'Female', 'quezon city', 'nidea@gmail.com', '09987979888', 'erlin', 'erlin', 'Active', '2021-11-19'),
  (7, 'STDNT-3097862', 'Noe', 'Lotivo', 'Gonzales', 'STEM', 'Grade 12', '2005-02-25', 'Male', 'Purok 6 Sitio Makokak, Brgy. Sto. Toribio, Lipa City', 'noegonzales781@gmail.com', '09309874255', 'noeg', 'gonzales25', 'Active', '2023-03-10'),
  (8, 'STDNT-003343', 'user', 'user', 'u', 'STEM', 'Grade 11', '2006-03-12', 'Female', 'bulcan', 'user@gmail.com', '0987654321', 'user', 'user321', 'Active', '2023-03-11')
on conflict (student_id) do nothing;

insert into public.tbl_usermanagement (
  user_id, complete_name, designation, email_address, phone_number, username, password, status, role
) values
  (4, 'Noe Gonzales', 'Programmer', 'noegonzales@gmail.com', '09309784255', 'admin', 'admin123', 'Active', '')
on conflict (user_id) do nothing;

insert into public.tbl_documentrequest (
  request_id, control_no, "studentID_no", document_name, purpose_ofrequesting, no_ofcopies,
  date_request, date_releasing, processing_officer, status, "reference number", remarks,
  student_id, notif
) values
  (1, 'CTRL-6922', 'STDNT-23983', 'TOR', 'for college admission', '20 copies', '2021-11-23', '2021-11-26', 'Admin admin', 'Pending', '2023-03-11 16:10:46', '', 2, 1),
  (2, 'CTRL-2902', 'STDNT-23983', 'DIPLOMA', 'for college admission', '10 copies', '2021-11-22', '2021-11-29', 'Noe Gonzales', 'Pending', '2023-03-11 16:10:46', '', 2, 1),
  (3, 'CTRL-0335', 'STDNT-3363233', 'GRADING', 'for college admission', '40 copies', '2021-11-24', '2021-11-26', 'Noe Gonzales', 'Ready', '2023-03-11 16:10:46', '', 5, 1),
  (4, 'CTRL-03237', 'STDNT-3097862', 'COE', 'for college admission', '1', '2005-02-25', '2023-04-04', 'Noe Gonzales', 'Received', '2023-03-11 16:10:46', '', 7, 1),
  (5, 'CTRL-7024', 'STDNT-0433220', 'FORM 137', '', '1', '2023-03-25', '', '', 'Received', '', '', 4, 0)
on conflict (request_id) do nothing;

select setval(pg_get_serial_sequence('public.tbl_strand', 'strand_id'), coalesce(max(strand_id), 1), true) from public.tbl_strand;
select setval(pg_get_serial_sequence('public.tbl_student', 'student_id'), coalesce(max(student_id), 1), true) from public.tbl_student;
select setval(pg_get_serial_sequence('public.tbl_usermanagement', 'user_id'), coalesce(max(user_id), 1), true) from public.tbl_usermanagement;
select setval(pg_get_serial_sequence('public.tbl_documentrequest', 'request_id'), coalesce(max(request_id), 1), true) from public.tbl_documentrequest;

commit;
